/**
 * Supabase client configuration for the Multimodal Healthcare Diagnostic System.
 *
 * To connect your database:
 *   1. Go to https://supabase.com → your project → Settings → API
 *   2. Copy "Project URL" → paste into VITE_SUPABASE_URL below (or .env)
 *   3. Copy "anon public" key → paste into VITE_SUPABASE_ANON_KEY below (or .env)
 */

import { createClient } from '@supabase/supabase-js'

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL as string
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY as string

if (!supabaseUrl || !supabaseAnonKey) {
  console.warn(
    '[Supabase] Missing VITE_SUPABASE_URL or VITE_SUPABASE_ANON_KEY. ' +
    'Create a .env file in the frontend/ directory or set them in Vite env.'
  )
}

export const supabase = createClient(
  supabaseUrl || 'https://placeholder.supabase.co',
  supabaseAnonKey || 'placeholder-key'
)

// ---------------------------------------------------------------------------
// Types matching the Supabase `patient_records` table
// ---------------------------------------------------------------------------
export interface PatientRecord {
  id?: string                     // UUID auto-generated by Supabase
  created_at?: string             // timestamp auto-generated
  patient_name: string
  gender: string
  age: number
  height: number
  weight: number
  bmi: number | null
  blood_glucose: number
  blood_pressure: number
  family_history: string
  physical_activity: string
  smoking_status: string
  medical_conditions: string
  symptoms: string[]
  hba1c: number
  insulin_level: number
  // Optional advanced
  pregnancies?: number | null
  skin_thickness?: number | null
  diabetes_pedigree?: number | null
  cholesterol?: number | null
  heart_rate?: number | null
  oxygen_saturation?: number | null
  // Prediction results
  prediction?: string | null
  confidence?: number | null
  clinical_interpretation?: string | null
}

// ---------------------------------------------------------------------------
// Helper: save a patient record to Supabase
// ---------------------------------------------------------------------------
export async function savePatientRecord(record: PatientRecord): Promise<{
  data: PatientRecord | null
  error: string | null
}> {
  try {
    const { data, error } = await supabase
      .from('patient_records')
      .insert([record])
      .select()
      .single()

    if (error) {
      console.error('[Supabase] Insert error:', error.message)
      return { data: null, error: error.message }
    }
    return { data, error: null }
  } catch (err: any) {
    console.error('[Supabase] Unexpected error:', err)
    return { data: null, error: err.message || 'Unknown error' }
  }
}
